[13.0][IMP] mrp_unbuild_bom_cust_qty: Change product_qty function to be reu…
solvosci/slv-manufacture pull request #65
Opened 2024-04-22 10:17 UTC by adriresu

…sable

2024-04-23 07:39 UTC, dalonsod requested changes

2024-04-23 07:39 UTC, dalonsod commented on mrp_unbuild_bom_cust_qty/models/mrp_unbuild.py
> +            unbuild.product_qty = self._get_product_qty_from_bom_totals() if self._get_product_qty_from_bom_totals() > 0 else 1
With this line total calculation is unnecessary made twice. Please reduce processing:
```suggestion
            total_qty = self._get_product_qty_from_bom_totals()
            unbuild.product_qty = total_qty if total_qty > 0 else 1
```

2024-04-23 16:16 UTC, dalonsod commented on mrp_unbuild_bom_cust_qty/models/mrp_unbuild.py
> +            total_qty = self._get_product_qty_from_bom_totals()
Grrr don't use `self` within loop and `multi` method!!

2024-04-24 13:55 UTC, adriresu commented on mrp_unbuild_bom_cust_qty/models/mrp_unbuild.py
> +            total_qty = self._get_product_qty_from_bom_totals()
Done

2024-04-24 14:41 UTC, dalonsod commented
OK, could you squash commits?

@ChristianSantamaria could we test it in AluTest environment?

2024-04-25 06:20 UTC, ChristianSantamaria commented
@dalonsod Squashed, rebased and tested in Test enviroment :+1:

2024-04-25 07:07 UTC, dalonsod commented
Great! Added @adriresu to contributors and extra commit with README update

2024-04-25 07:07 UTC, merged