[15.0][IMP] mrp_project_analytic: Add mark_analytic_mrp_from_child
solvosci/slv-manufacture pull request #78
Opened 2024-06-11 08:14 UTC by Anxo82

Add mark_analytic_mrp_from_child for to mark  the new field analytic_mrp_from_child to true the journal items from child productions

2024-06-11 08:15 UTC, Anxo82 commented
Review please

2024-06-11 08:26 UTC, dalonsod requested changes
Only code review :+1: 

Only cosmetic changes before I test it, see comment. And also, add in `DESCRIPTON.rst` a breif description for added functionality (in a more human readable way than commit title)

2024-06-11 08:26 UTC, dalonsod commented on mrp_project_analytic/views/account_move_line_view.xml
> +                <field name="analytic_mrp_from_child" widget="boolean_toggle"/>
Add control access:
```suggestion
                <field name="analytic_mrp_from_child" widget="boolean_toggle" groups="analytic.group_analytic_accounting"/>
```

like

https://github.com/odoo/odoo/blob/c44aece8c91dffd943f66293cee629c33207b241/addons/account/views/account_move_views.xml#L72C75-L72C118

2024-06-11 10:04 UTC, Anxo82 commented
Review please

2024-06-11 12:00 UTC, dalonsod commented on mrp_project_analytic/readme/DESCRIPTION.rst
> +to true the debit journal items from child productions.
Better this:
```suggestion

Also adds a new check that identifies those debit journal items linked to MRP consume moves that are actually come from child productions.
```

2024-07-03 09:18 UTC, dalonsod approved these changes
:+1: please squash both commits in this case (we won't cherry-pick anything that could justify separate changes in two commits)

2024-07-03 09:26 UTC, Anxo82 commented
Review please

2024-07-03 09:31 UTC, dalonsod commented
Let's merge!

2024-07-03 09:31 UTC, merged