[13.0][IMP] mrp_unbuild_cust_alu_analytics_maintenance: Add maintenance_equipment_id to tree view and change translation
solvosci/slv-manufacture pull request #88
Opened 2024-10-22 08:16 UTC by Anxo82

Add maintenance_equipment_id to tree view and change translation

2024-10-22 08:16 UTC, Anxo82 commented
@ChristianSantamaria @dalonsod Review please.
Thanks

2024-10-22 18:20 UTC, dalonsod reviewed
See comments.

2024-10-22 18:20 UTC, dalonsod commented on mrp_unbuild_cust_alu_analytics_maintenance/views/mrp_unbuild_incidence_views.xml
> +                <field name="maintenance_equipment_id"/>
Make it optional and shown by default

2024-10-22 18:20 UTC, dalonsod commented on mrp_unbuild_cust_alu_analytics_maintenance/views/mrp_unbuild_incidence_views.xml
> +    <record id="mrp_unbuild_incidence_tree_inherit_view" model="ir.ui.view">
As added to tree view, I should add it to `search` view as well (searching for this file, and grouping too).

2024-10-23 06:56 UTC, Anxo82 commented
@ChristianSantamaria @dalonsod Review please.
Thanks

2024-10-23 07:37 UTC, dalonsod requested changes
See minor comments. When attended please @ChristianSantamaria update AluTest environment and I'll test it

2024-10-23 07:37 UTC, dalonsod commented on mrp_unbuild_cust_alu_analytics_maintenance/views/mrp_unbuild_incidence_views.xml
> +                <filter string="Machine" name="machine_filter"  domain="[('maintenance_equipment_id', '!=', False)]"/>
Proper label:

```suggestion
                <filter string="With Machine" name="machine_filter"  domain="[('maintenance_equipment_id', '!=', False)]"/>
```

2024-10-23 07:37 UTC, dalonsod commented on mrp_unbuild_cust_alu_analytics_maintenance/i18n/es.po
> +msgstr "Maquina"
Missing accent:

```suggestion
msgstr "Máquina"
```

2024-10-23 09:00 UTC, dalonsod commented
One very last thing @Anxo82 , manifest version isn't updated!

2024-10-23 10:18 UTC, Anxo82 commented
Done! Thanks

2024-10-23 10:32 UTC, dalonsod approved these changes
Let's go!!!

2024-10-23 10:32 UTC, merged